# Site
name: "Psychedelic Inspiration"
title: "Psychedelic Inspiration"
description: "Technology, Life and Everything in Between"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: ''
disqus: 'souvikg-com'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  souvik:
    name: Souvik
    display_name: Souvik
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: talkativeserious@gmail.com
    web: https://souvikg.com
    #twitter: https://twitter.com/wowthemesnet
    description: "Author of SouvikG.com, a tech enthusiast and a kiddish Dad ! I love to tinker with my grey matter. You are currently previewing my journal, where i note down my figments of imagination"
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
